import { StyleSheet } from "react-native"
import { responsiveHeight, responsiveWidth, responsiveFontSize } from "react-native-responsive-dimensions";
import colors from '../../services/contants/colors'
const styles = StyleSheet.create({
    container: {
        width: responsiveWidth(45),
        height: responsiveHeight(10),
        // backgroundColor: colors.appColorWhite,
        borderRadius: 10,
        // alignSelf: 'center',
        alignItems: 'center',
        // justifyContent: 'space-between',
        // elevation: 10,
        // shadowColor: '#000',
        // shadowOffset: { width: 0, height: 2 },
        // shadowOpacity: 0.5,
        // shadowRadius: 2,
        // marginVertical: responsiveHeight(1),
        marginHorizontal: responsiveWidth(5),
        flexDirection: 'row',
        // paddingHorizontal: responsiveWidth(5),
    },
    staffImage: {
        width: responsiveWidth(15),
        height: responsiveWidth(15),
        borderRadius: 100,
        borderWidth: 1,
        // elevation: 10,
        // shadowColor: '#000',
        // shadowOffset: { width: 0, height: 2 },
        // shadowOpacity: 0.5,
        // shadowRadius: 2,
        margin: responsiveWidth(1),
        borderColor: colors.appColorLightBlue,
        zIndex: 10,
    },
    nameSelectedContainer: {
        elevation: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.5,
        shadowRadius: 2,
        backgroundColor: colors.appColorLightBlue,
        height: responsiveWidth(11.5),
        zIndex: 1,
        marginLeft: -responsiveWidth(3.5),
        width: responsiveWidth(40),
        justifyContent: 'center',
        paddingLeft: responsiveWidth(3.5),
        borderTopRightRadius: 10,
        borderBottomRightRadius: 10,
    },
    nameUnselectedContainer: {
        elevation: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.5,
        shadowRadius: 2,
        backgroundColor: colors.appColorWhite,
        height: responsiveWidth(11.5),
        zIndex: 1,
        marginLeft: -responsiveWidth(3.5),
        width: responsiveWidth(40),
        justifyContent: 'center',
        paddingLeft: responsiveWidth(3.5),
        borderTopRightRadius: 10,
        borderBottomRightRadius: 10,
    },
    nameSelectedText:{
        color: colors.appColorWhite,
        fontWeight: 'bold',
        fontSize: responsiveFontSize(2),
    },
    nameUnselectedText:{
        color: colors.appColorDarkBlue,
        fontWeight: 'bold',
        fontSize: responsiveFontSize(2),
    },
});
export default styles